name: Super Linter

on:
  push:
    branches: [ main, '**' ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: super-linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: github/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Reduce noise and avoid 403 status API issues, only lint relevant languages for this repo
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          FILTER_REGEX_EXCLUDE: '(^demo/target/|^\.mvn/|^demo/\.vscode/)'
          # Enable only the core linters we need (include mode)
          VALIDATE_JAVA: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
